hasura/go-graphql-client

- README.md
- go.mod
- go.sum
- graphql.go
- graphql_test.go
In the case we developers want to decode JSON response ourself. Moreover, the default `UnmarshalGraphQL` function isn't ideal with complicated nested interfaces
```Go
func (c *Client) QueryRaw(ctx context.Context, q interface{}, variables map[string]interface{}) (*json.RawMessage, error)
func (c *Client) MutateRaw(ctx context.Context, q interface{}, variables map[string]interface{}) (*json.RawMessage, error)
func (c *Client) NamedQueryRaw(ctx context.Context, name string, q interface{}, variables map[string]interface{}) (*json.RawMessage, error)
func (c *Client) NamedMutateRaw(ctx context.Context, name string, q interface{}, variables map[string]interface{}) (*json.RawMessage, error)
```
> Add raw query and mutation response methods

- graphql_test.go
- internal/jsonutil/graphql.go
- internal/jsonutil/graphql_test.go
This is a port of @cameronbrunner fix to the original repo. See https://github.com/shurcooL/graphql/pull/41
It also contains fixes to `quest_test.go`
> Support raw json fields

- README.md
- internal/jsonutil/graphql.go
- internal/jsonutil/graphql_test.go
- query.go
- query_test.go
Suppose I can create user like this
```GraphQL
mutation($login: String!) {
createUser(login: $login) { login }
}
variables {
"login": "grihabor"
}
```
Now I'd like to create multiple users in single request
```GraphQL
mutation($login1: String!, $login2: String!, $login3: String!) {
createUser(login: $login1) { login }
createUser(login: $login2) { login }
createUser(login: $login3) { login }
}
variables {
"login1": "grihabor",
"login2": "diman",
"login3": "indigo",
}
```
It would be convenient to implement it in code with ordered map
```Go
type CreateUser struct {
Login graphql.String
}
m := [][2]interface{}{
{"createUser(login: $login1)", &CreateUser{}},
{"createUser(login: $login2)", &CreateUser{}},
{"createUser(login: $login3)", &CreateUser{}},
}
variables := map[string]interface{}{ …
```
> Allow building queries and mutations from ordered maps ([][2]string)

- internal/jsonutil/graphql.go
- internal/jsonutil/graphql_test.go
It's a followup for #20, which introduced `[][2]interface{}` to allow building arbitrary queries at runtime. But when we access `interface{}` in reflect we need to call `v.Elem()` to get the actual object inside. This is properly done in the pr
> Call v.Elem() to cast interface{} away (followup for #20)

- graphql.go
- subscription.go
Right now dealing with errors is not very graceful as you need to rely on parsing `err.Error()`. Exporting the error and adding `extensions` isn't ideal either but at least it let's you try to treat hasura errors a bit more gracefully and do things like:
```
func parseGraphqlError(err error) error {
var ghErr graphql.Errors
if errors.As(err, &ghErr) {
code, ok := ghErr[0].Extensions["code"]
if !ok {
return err
}
switch code {
case "access-denied":
...
default:
return err
}
}
return err
}
```
allowing you to treat errors you may be interested in.
> export Errors and add extensions to allow clients parse the error

- graphql.go
The purpose of this PR is to allow users of this library to modify the outgoing request. It is useful as it allows you to set authentication headers without having to write a custom http client (ref. https://github.com/shurcooL/graphql/issues/28#issuecomment-464713908)
The mechanism implemented for this has two purposes:
1. It maintains backwards compatibility
2. It allows reusing the same client amongst slightly different "configurations". This allows you to have one single http client in multitenant applications with different authentication headers.
You can see a silly proof of concept below to illustrate how different requests can tweak the header slightly different while reusing the same TCP socket for performance reasons:
```
package main
import (
"context"
"fmt"
"net/http"
"sync" …
```
> add mechanism to modify outgoing http request

- internal/jsonutil/graphql.go
- internal/jsonutil/graphql_test.go
- query.go
- query_test.go
This change allows us to specify that a field in a struct has a
scalar GraphQL type associated with it. This is done by adding
the tag `scalar:"true"` to the field. This would allow us to
- Avoid expansion of the field during request query generation,
even when the golang type of the field is a struct
- When the response is decoded, the value is simply JSON decoded,
instead of the much stricter GraphQL decode.
- Types like map[string]interface{}, json.RawMessage, etc should
work as far as the corresponding fields are marked as scalar
> Allow tagging of the field as having a scalar GraphQL type

- subscription.go
Close method calls Unsubscribe which tries to Lock already locked mutex.
> Fix a race in Close method of SubscriptionClient

- README.md
- graphql.go
- graphql_test.go
- query.go
- query_test.go
- subscription.go
Enable debug mode with the `WithDebug` function. If the request is failed, the request and response information will be included in the `extensions[].internal` property.
```json
{
"errors": [
{
"message":"Field 'user' is missing required arguments: login",
"extensions": {
"internal": {
"request": {
"body":"{\"query\":\"{user{name}}\"}",
"headers": {
"Content-Type": ["application/json"]
}
},
"response": {
"body":"{\"errors\": [{\"message\": \"Field 'user' is missing required arguments: login\",\"locations\": [{\"line\": 7,\"column\": 3}]}]}",
"headers": {
"Content-Type": ["application/json"]
}
}
}
},
"locations": [
{
"line":7,
"column":3
}
]
}
]
}
```
Because the GraphQL query string is generated in runtime using reflection, it isn't really safe. To assure the GraphQL query is expected, …
> add debug modes and expose GraphQL builder functions for unit tests

- README.md
- graphql_test.go
- query.go
- query_test.go
Skip GraphQL field with hyphen tag. Inspired from `encoding/json` library. 
```go
struct {
Viewer struct {
ID         interface{} `graphql:"-"`
Login      string
CreatedAt  time.Time `graphql:"-"`
DatabaseID int
}
}
// Output
// {viewer{login,databaseId}}
```
> Skip field with hyphen graphql tag

- graphql.go
This PR adds a method that allows you to execute pre-built queries. While using reflection to build queries is convenient as you get some resemblance of type safety it gets very cumbersome when you need to create queries semi-dynamically. For instance, imagine you are building a CLI tool to query data from a graphql endpoint and you want users to be able to narrow down the query by passing cli flags or something. In that case you could do something like:
``` go
// filters would be built dynamically somehow from the command line flags
filters := []string{
`fieldA: {subfieldA: {_eq: "a"}}`,
`fieldB: {_eq: "b"}`,
...
}
query := "query{something(where: {" + strings.Join(filters, ", ") + "}){id}}"
res := struct {
Somethings []Something
}{}
if err := client.DoWithQuery(ctx, query, &res, …
```
> added method to execute queries already pre-built

- query.go
- query_test.go
- type.go
```go
type UserReviewInput struct {
Review String
UserID String
}
func (u UserReviewInput) GetGraphQLType() string { return "user_review_input" }
variables := map[string]interface{}{
"input": UserReviewInput{}
}
//query arguments without GetGraphQLType() defined
//($input: UserReviewInput!)
//query arguments with GetGraphQLType() defined:w
//($input: user_review_input!)
```
> Allow specifying GraphQL type name for a particular type

- README.md
- subscription.go
Rename `SubscribeRaw` to `Exec` to make it consistent with the HTTP client
> add subscription Exec alias for pre-built query

- README.md
- example/subscription/client.go
- example/subscription/main.go
- subscription.go
- subscription_test.go
- Fix the deadlock issue that the subscription client can't receive error events from the channel.
- Close the connection when there is no running subscription
- add a particular error that stops the subscription inside the callback 
```go
subscriptionId, err := client.Subscribe(&query, nil, func(dataValue *json.RawMessage, errValue error) error {
// ...
// return this error to stop the subscription in the callback
return ErrSubscriptionStopped
})
```
> fix subscription hanging on error and add a stop subscription option inside the callback

- README.md
- doc.go
- example/subscription/client.go
- graphql.go
- graphql_test.go
- subscription.go
- subscription_test.go
This PR adds `ExecRaw` method that returns a raw json message.
```Go
query := `query{something(where: { foo: { _eq: "bar" }}){id}}`
var res struct {
Somethings []Something `json:"something"`
}
raw, err := client.ExecRaw(ctx, query, map[string]any{}) 
if err != nil {
panic(err)
}
err = json.Unmarshal(raw, &res)
```
**Breaking change**: currently `QueryRaw`, `MutateRaw` and `Subscribe` methods return `*json.RawMessage`. This output type is redundant to be decoded. The output type should be changed to `[]byte`.
```Go
var subscription struct {
Me struct {
Name graphql.String
}
}
subscriptionId, err := client.Subscribe(&query, nil, func(dataValue []byte, errValue error) error {
if errValue != nil {
// handle error
// if returns error, it will failback to `onError` event
return nil
}
data := …
```
> introduce ExecRaw and change the output type of Raw methods

- query.go
- query_test.go
close https://github.com/hasura/go-graphql-client/issues/48
Because the query parser infers and creates a new instance from the reflection type, it doesn't work if the `GetGraphQLType` method returns the dynamic type of struct property from the input variable.
```go
type customTypeHint struct {
Hint string
}
func (cth *customTypeHint) GetGraphQLType() string {
return cth.hint
}
q := queryArguments(variables map[string]interface{} {
"foo": customTypeHint{ Hint: "bar" }
})
// expected
// $foo:bar!
// actual
// $foo:!
```
> fix dynamic GraphQLType interface

- graphql.go
Allow to pass a custom HTTP client when creating the GraphQL client, instead of just accepting the `*http.Client`, that way people can use clients that have support for retry and backoff. Eg. [Heimdall](https://github.com/gojek/heimdall) or [Resty](https://github.com/go-resty/resty)
> Allow to use custom HTTP clients

- subscription.go
- subscription_graphql_ws.go
- subscriptions_transport_ws.go
This PR enables optionally provided an `onConnectionAlive` function that will be called when connection alive message is received by the subscription.
This is useful for implementing healthchecks on top of the connection status, as instructed by connection alive messages (actual message differs per protocol).
> feat: subscription client provide connection alive callback

- subscription.go
- subscription_graphql_ws.go
- subscriptions_transport_ws.go
When a message is received from a subscription that was just unsubscribed, a panic will be raised due to having an empty subscription that contains a nil handler.
Refactored `GetSubscription` to return nil when no subscription is found and added guard clause to prevent using it for `data` messages.
> fix: prevent panic on late message after unsubscribed subscription

- .github/workflows/test.yml
- README.md
- query.go
- query_test.go
- subscription.go
- subscription_graphql_ws.go
- subscription_graphql_ws_test.go
- subscription_test.go
- subscriptions_transport_ws.go
- subscriptions_transport_ws_test.go
Fix https://github.com/hasura/go-graphql-client/issues/80
The PR improves the subscription client with a new event and settings
**Event**
```go
// OnSubscriptionComplete event is triggered when the subscription receives 
// a terminated message from the server
client.OnSubscriptionComplete(fn func(sub Subscription))
```
**Settings**
```go
client.
// the client should exit when all subscriptions were closed, default true
WithExitWhenNoSubscription(false).
// WithRetryStatusCodes allow retry the subscription connection when receiving one of these codes
// the input parameter can be number string or range, e.g 4000-5000 
WithRetryStatusCodes([]string{"4000", "4000-4050"})
```
> improve the subscription life cycle event and add new settings

- subscriptions_transport_ws.go
In the OnMessage function of the protocol graphqlWS and subscriptionsTransportWS, errors with message type error are inconsistent
Expected consistent error handling
> fix bug:  Transport WS  On Error Message not invoke subscription handler 

- .github/workflows/test.yml
- go.mod
- go.sum
- graphql.go
- graphql_test.go
- Update Github Actions since these actions are built on [deprecated node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) tagged actions.
- Update Go module version to 1.20. The EOL of current Go version 1.16 was on [15 Mar 2022](https://endoflife.date/go).
- Update `ioutil.ReadAll` to `io.ReadAll` 
All go.mod updates were a result of setting `go 1.20` in `go.mod` then running `go get -u ./...` followed by `go mod tidy`.
> update gh actions and go versions, update deprecated ioutil

- graphql.go
- query.go
This PR sets the operation name not only in the query string but also in the request payload. 
My usecase is that the server (gqlgen) only recognises the operation name if it exists in the payload and on the server I need the name for logging purposes.
> Set operation name on request payload

- go.mod
- subscription.go
Some servers requires the client to send ping to prevent connection from being broken due to idling. We have added `WithKeepAlive` which accepts `time.Duration` that will be use as interval for doing a continuous ping to the server. This is also implemented in npm package [graphql-ws](https://the-guild.dev/graphql/ws/docs/modules/use_ws#parameters). 
`WithRetryDelay` makes retry delay customizable. If not set it will use the default (currently hard coded 1 second).
> feat: added optional WithKeepAlive and WithRetryDelay

- .github/workflows/test.yml
- README.md
- example/graphql-ws-bc/README.md
- example/graphql-ws-bc/client/main.go
- example/graphql-ws-bc/server/.gitignore
- example/graphql-ws-bc/server/index.ts
- example/graphql-ws-bc/server/package-lock.json
- example/graphql-ws-bc/server/package.json
- example/graphql-ws-bc/server/schema.ts
- example/graphql-ws-bc/server/tsconfig.json
- example/hasura/client/graphql-ws/client.go
- example/hasura/client/subscriptions-transport-ws/client.go
- example/realworld/main.go
- example/subscription/client.go
- example/subscription/main.go
- example/tibber/client.go
- graphql.go
- pkg/jsonutil/graphql_test.go
- query.go
- subscription.go
- subscription_graphql_ws_test.go
- subscription_test.go
- subscriptions_transport_ws_test.go
Add more WebSocket options that are supported natively by the [nhooyr.io/websocket](https://github.com/nhooyr/websocket) client such as HTTP header and compression.
```go
// WebsocketOptions allows implementation agnostic configuration of the websocket client
type WebsocketOptions struct {
// HTTPClient is used for the connection.
// Its Transport must return writable bodies for WebSocket handshakes.
// http.Transport does beginning with Go 1.12.
HTTPClient *http.Client
// HTTPHeader specifies the HTTP headers included in the handshake request.
HTTPHeader http.Header
// Host optionally overrides the Host HTTP header to send. If empty, the value
// of URL.Host will be used.
Host string
// CompressionMode controls the compression mode.
// Defaults to CompressionDisabled.
//
// See docs on …
```
> feat: add more WebSocket options for subscription client

- graphql.go
- graphql_test.go
Fixes #127.
Adds `Unwrap()` to `Error` and `Errors`.
> Add Unwrap() implementations for Error types

- graphql.go
- graphql_test.go
This PR adds a new error type: ErrResponseStatusNotOK
This error contains the status code and response body which were previously returned as the error message.
This change has two benefits:
* Allows systems that depend on this package to be able to check for error response codes by using go's inbuilt errors package and matching on the error code, rather than string matching on the error message.
* ~Returns the body of the request as an `io.Reader` to reduce unnecessary data being passed around.~
```go
// Before 
err := client.Query(ctx, query, variables)
if err != nil {
serviceErrRegex := regexp.MustCompile(`^non-200 OK status code: 5\d\d.+`)
if serviceErrRegex.MatchString(err.Error()) {
// handle 5xx status response
}
}
```
```go
// After
err := client.Query(ctx, query, variables) …
```
> returns NetworkError when the request response returns a non-200 http status code

- README.md
- example/subscription/subscription_test.go
- graphql.go
- graphql_test.go
- option.go
- query.go
- query_test.go
The response map may also contain an entry with key `extensions`. To decode this field you need to bind a struct or map pointer. The client will optionally unmarshal the field using json decoder.
```go
var q struct {
User struct {
ID   string `graphql:"id"`
Name string `graphql:"name"`
}
}
var ext struct {
ID     int    `json:"id"`
Domain string `json:"domain"`
}
err := client.Query(context.Background(), &q, map[string]interface{}{}, graphql.BindExtensions(&ext))
if err != nil {
t.Fatal(err)
}
```
> feat: decode extensions from response via BindExtensions option

- README.md
- example/subscription/go.mod
- example/subscription/go.sum
- go.mod
- go.sum
- subscription.go
- subscription_graphql_ws_test.go
- subscriptions_transport_ws_test.go
`nhooyr.io/websocket` is deprecated and stopped working (my CI builds failed)
the new repo is `github.com/coder/websocket`
related info:
https://pkg.go.dev/nhooyr.io/websocket
https://coder.com/blog/websocket
also we need a version bump to fix the examples directory.
> migrate nhooyr.io/websocket to github.com/coder/websocket

- README.md
- graphql.go
- graphql_test.go
- option.go
- query.go
- subscription_graphql_ws_test.go
close https://github.com/hasura/go-graphql-client/issues/161
Introduce a new `BindResponseHeaders` option to retrieve response headers via binding.
```go
headers := http.Header{}
err := client.Query(context.TODO(), &q, nil, graphql.BindResponseHeaders(&headers))
if err != nil {
panic(err)
}
fmt.Println(headers.Get("content-type"))
// application/json
```
> feat: introduce BindResponseHeaders option

- .github/workflows/lint.yml
- .github/workflows/test.yml
- README.md
- example/hasura/docker-compose.yaml
- example/subscription/subscription_test.go
- subscription.go
- subscription_graphql_ws.go
- subscription_graphql_ws_test.go
- subscriptions_transport_ws.go
- subscriptions_transport_ws_test.go
close https://github.com/hasura/go-graphql-client/issues/160
- The main runner will be a singleton. Get rid of the recursive loop to avoid goroutine leaks
- Enhance the error handling. Add 2 new timeout settings `WithConnectionInitialisationTimeout` and `WithWebsocketConnectionIdleTimeout` to handle errors when the server is unresponsive. Check out [the docs](https://github.com/hasura/go-graphql-client/blob/32a4f6483e3aae1249f56e3d54124100be18bca0/README.md#connection-initialisation-timeout) for more details.
> fix: subscription goroutine leaks

- example/tibber/client.go
We have recently started seeing big amounts of badly having clients connecting to Tibber websocket API (reconnecting super frequently even on error - basically DDOSing us) using user agent `go-graphql-client/0.9.0`.
This PR is to indicate that the user agent should be kept up-to-date. We might need to ban `go-graphql-client/0.9.0` from connecting entirely.
> Indicate user agent should be descriptive

- example/subscription/go.mod
- example/subscription/go.sum
- example/subscription/subscription_test.go
- subscription.go
- subscription_graphql_ws.go
- subscriptions_transport_ws.go
This pull request introduces several enhancements to the WebSocket-based subscription system, focusing on improved logging, connection lifecycle management, and test coverage. Key changes include adding metadata to logging, tracking WebSocket connection statistics, and updating tests to verify connection states.
* Updated `SubscriptionContext.Log` to accept a `metadata` map instead of a `source` string, enabling richer logging details. Metadata now includes `session_id` and `connection_id` where applicable. (`subscription.go`, [[1]](diffhunk://#diff-828fe8a645cf1a278fb0dfdca1eac3d6b4c691415c66dbe854d6286e2578031bL157-R168) [[2]](diffhunk://#diff-828fe8a645cf1a278fb0dfdca1eac3d6b4c691415c66dbe854d6286e2578031bL372-R386) [[3]](diffhunk://#diff-828fe8a645cf1a278fb0dfdca1eac3d6b4c691415c66dbe8 …
> feat: improve subscription logging and metrics

- subscription.go
* Updated the `source` field in error logs from `"client"` to `"server"` in the `run` method of `SubscriptionContext` to ensure accurate representation of the error origin.
* Rename method `AddDeadConnection` to `AddClosedConnection`.
> fix: subscription logging typo

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .golangci.yml
- graphql.go
- graphql_test.go
The HTTP client can automatically decompress gzip content by the `Content-Encoding` header.  No need to do the unnecessary decompression step.
https://github.com/hasura/go-graphql-client/issues/181
> fix: remove unnecessary gzip decompression   
